const dados = [
  {
    nomePagador: "Henrique Castro",
    numeroNota: 1,
    dataEmissao: "21/01/2023",
    dataCobranca: "05/09/2023",
    dataPagamento: null,
    valorNota: "232.00",
    documentoNotaFiscal: "NF1",
    documentoBoleto: "Boleto1",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "André Silva",
    numeroNota: 2,
    dataEmissao: "27/07/2023",
    dataCobranca: "20/09/2023",
    dataPagamento: "09/12/2023",
    valorNota: "483.00",
    documentoNotaFiscal: "NF2",
    documentoBoleto: "Boleto2",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Renata Pereira",
    numeroNota: 3,
    dataEmissao: "25/02/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "499.00",
    documentoNotaFiscal: "NF3",
    documentoBoleto: "Boleto3",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Marcos Fernandes",
    numeroNota: 4,
    dataEmissao: "11/06/2023",
    dataCobranca: "30/11/2023",
    dataPagamento: "09/12/2023",
    valorNota: "166.00",
    documentoNotaFiscal: "NF4",
    documentoBoleto: "Boleto4",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 5,
    dataEmissao: "19/07/2023",
    dataCobranca: "20/08/2023",
    dataPagamento: null,
    valorNota: "608.00",
    documentoNotaFiscal: "NF5",
    documentoBoleto: "Boleto5",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Maria Oliveira",
    numeroNota: 6,
    dataEmissao: "05/06/2023",
    dataCobranca: "12/10/2023",
    dataPagamento: "14/09/2023",
    valorNota: "720.00",
    documentoNotaFiscal: "NF6",
    documentoBoleto: "Boleto6",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Carolina Almeida",
    numeroNota: 7,
    dataEmissao: "20/01/2023",
    dataCobranca: "13/09/2023",
    dataPagamento: "13/11/2023",
    valorNota: "364.00",
    documentoNotaFiscal: "NF7",
    documentoBoleto: "Boleto7",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Luciana Costa",
    numeroNota: 8,
    dataEmissao: "15/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "385.00",
    documentoNotaFiscal: "NF8",
    documentoBoleto: "Boleto8",
    statusNota: "Emitida",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 9,
    dataEmissao: "28/08/2023",
    dataCobranca: "21/09/2023",
    dataPagamento: null,
    valorNota: "914.00",
    documentoNotaFiscal: "NF9",
    documentoBoleto: "Boleto9",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Gabriel Sousa",
    numeroNota: 10,
    dataEmissao: "20/08/2023",
    dataCobranca: "09/12/2023",
    dataPagamento: null,
    valorNota: "367.00",
    documentoNotaFiscal: "NF10",
    documentoBoleto: "Boleto10",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Juliana Almeida",
    numeroNota: 11,
    dataEmissao: "28/01/2023",
    dataCobranca: "20/03/2023",
    dataPagamento: null,
    valorNota: "766.00",
    documentoNotaFiscal: "NF11",
    documentoBoleto: "Boleto11",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Paulo Mendes",
    numeroNota: 12,
    dataEmissao: "02/01/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "929.00",
    documentoNotaFiscal: "NF12",
    documentoBoleto: "Boleto12",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Juliana Almeida",
    numeroNota: 13,
    dataEmissao: "25/05/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "977.00",
    documentoNotaFiscal: "NF13",
    documentoBoleto: "Boleto13",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 14,
    dataEmissao: "01/01/2023",
    dataCobranca: "04/03/2023",
    dataPagamento: "24/07/2023",
    valorNota: "825.00",
    documentoNotaFiscal: "NF14",
    documentoBoleto: "Boleto14",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Mariana Silva",
    numeroNota: 15,
    dataEmissao: "18/02/2023",
    dataCobranca: "22/04/2023",
    dataPagamento: null,
    valorNota: "970.00",
    documentoNotaFiscal: "NF15",
    documentoBoleto: "Boleto15",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Diego Lima",
    numeroNota: 16,
    dataEmissao: "12/02/2023",
    dataCobranca: "04/07/2023",
    dataPagamento: "19/07/2023",
    valorNota: "226.00",
    documentoNotaFiscal: "NF16",
    documentoBoleto: "Boleto16",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 17,
    dataEmissao: "03/03/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "783.00",
    documentoNotaFiscal: "NF17",
    documentoBoleto: "Boleto17",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Gustavo Rocha",
    numeroNota: 18,
    dataEmissao: "19/03/2023",
    dataCobranca: "26/08/2023",
    dataPagamento: null,
    valorNota: "647.00",
    documentoNotaFiscal: "NF18",
    documentoBoleto: "Boleto18",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Carlos Mendes",
    numeroNota: 19,
    dataEmissao: "31/05/2023",
    dataCobranca: "08/12/2023",
    dataPagamento: null,
    valorNota: "253.00",
    documentoNotaFiscal: "NF19",
    documentoBoleto: "Boleto19",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Juliana Almeida",
    numeroNota: 20,
    dataEmissao: "09/09/2023",
    dataCobranca: "21/10/2023",
    dataPagamento: null,
    valorNota: "273.00",
    documentoNotaFiscal: "NF20",
    documentoBoleto: "Boleto20",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 21,
    dataEmissao: "22/04/2023",
    dataCobranca: "14/10/2023",
    dataPagamento: "15/11/2023",
    valorNota: "719.00",
    documentoNotaFiscal: "NF21",
    documentoBoleto: "Boleto21",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Roberto Costa",
    numeroNota: 22,
    dataEmissao: "03/05/2023",
    dataCobranca: "15/10/2023",
    dataPagamento: null,
    valorNota: "697.00",
    documentoNotaFiscal: "NF22",
    documentoBoleto: "Boleto22",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 23,
    dataEmissao: "01/07/2023",
    dataCobranca: "18/07/2023",
    dataPagamento: "03/08/2023",
    valorNota: "702.00",
    documentoNotaFiscal: "NF23",
    documentoBoleto: "Boleto23",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Paulo Mendes",
    numeroNota: 24,
    dataEmissao: "12/04/2023",
    dataCobranca: "12/08/2023",
    dataPagamento: "30/11/2023",
    valorNota: "279.00",
    documentoNotaFiscal: "NF24",
    documentoBoleto: "Boleto24",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 25,
    dataEmissao: "16/06/2023",
    dataCobranca: "19/09/2023",
    dataPagamento: "14/11/2023",
    valorNota: "512.00",
    documentoNotaFiscal: "NF25",
    documentoBoleto: "Boleto25",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Carlos Costa",
    numeroNota: 26,
    dataEmissao: "28/06/2023",
    dataCobranca: "29/06/2023",
    dataPagamento: "05/11/2023",
    valorNota: "596.00",
    documentoNotaFiscal: "NF26",
    documentoBoleto: "Boleto26",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Renata Pereira",
    numeroNota: 27,
    dataEmissao: "24/03/2023",
    dataCobranca: "01/04/2023",
    dataPagamento: null,
    valorNota: "574.00",
    documentoNotaFiscal: "NF27",
    documentoBoleto: "Boleto27",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Henrique Castro",
    numeroNota: 28,
    dataEmissao: "14/07/2023",
    dataCobranca: "20/09/2023",
    dataPagamento: null,
    valorNota: "195.00",
    documentoNotaFiscal: "NF28",
    documentoBoleto: "Boleto28",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Luciana Costa",
    numeroNota: 29,
    dataEmissao: "06/03/2023",
    dataCobranca: "17/04/2023",
    dataPagamento: "23/04/2023",
    valorNota: "413.00",
    documentoNotaFiscal: "NF29",
    documentoBoleto: "Boleto29",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Gabriel Sousa",
    numeroNota: 30,
    dataEmissao: "03/09/2023",
    dataCobranca: "23/10/2023",
    dataPagamento: null,
    valorNota: "310.00",
    documentoNotaFiscal: "NF30",
    documentoBoleto: "Boleto30",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Renata Rodrigues",
    numeroNota: 31,
    dataEmissao: "12/06/2023",
    dataCobranca: "20/11/2023",
    dataPagamento: null,
    valorNota: "248.00",
    documentoNotaFiscal: "NF31",
    documentoBoleto: "Boleto31",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Henrique Castro",
    numeroNota: 32,
    dataEmissao: "26/01/2023",
    dataCobranca: "29/04/2023",
    dataPagamento: null,
    valorNota: "677.00",
    documentoNotaFiscal: "NF32",
    documentoBoleto: "Boleto32",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Rodrigo Fernandes",
    numeroNota: 33,
    dataEmissao: "26/05/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "286.00",
    documentoNotaFiscal: "NF33",
    documentoBoleto: "Boleto33",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 34,
    dataEmissao: "09/04/2023",
    dataCobranca: "15/04/2023",
    dataPagamento: null,
    valorNota: "944.00",
    documentoNotaFiscal: "NF34",
    documentoBoleto: "Boleto34",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Simone Santos",
    numeroNota: 35,
    dataEmissao: "09/06/2023",
    dataCobranca: "20/06/2023",
    dataPagamento: null,
    valorNota: "830.00",
    documentoNotaFiscal: "NF35",
    documentoBoleto: "Boleto35",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 36,
    dataEmissao: "08/08/2023",
    dataCobranca: "08/11/2023",
    dataPagamento: null,
    valorNota: "791.00",
    documentoNotaFiscal: "NF36",
    documentoBoleto: "Boleto36",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Beatriz Almeida",
    numeroNota: 37,
    dataEmissao: "03/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "831.00",
    documentoNotaFiscal: "NF37",
    documentoBoleto: "Boleto37",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Gustavo Rocha",
    numeroNota: 38,
    dataEmissao: "16/01/2023",
    dataCobranca: "11/06/2023",
    dataPagamento: "29/07/2023",
    valorNota: "977.00",
    documentoNotaFiscal: "NF38",
    documentoBoleto: "Boleto38",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Clara Rocha",
    numeroNota: 39,
    dataEmissao: "09/07/2023",
    dataCobranca: "02/09/2023",
    dataPagamento: null,
    valorNota: "980.00",
    documentoNotaFiscal: "NF39",
    documentoBoleto: "Boleto39",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Viviane Rodrigues",
    numeroNota: 40,
    dataEmissao: "25/04/2023",
    dataCobranca: "24/09/2023",
    dataPagamento: "09/11/2023",
    valorNota: "140.00",
    documentoNotaFiscal: "NF40",
    documentoBoleto: "Boleto40",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Simone Santos",
    numeroNota: 41,
    dataEmissao: "21/05/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "858.00",
    documentoNotaFiscal: "NF41",
    documentoBoleto: "Boleto41",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Daniel Almeida",
    numeroNota: 42,
    dataEmissao: "23/01/2023",
    dataCobranca: "21/03/2023",
    dataPagamento: null,
    valorNota: "706.00",
    documentoNotaFiscal: "NF42",
    documentoBoleto: "Boleto42",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Alexandre Lima",
    numeroNota: 43,
    dataEmissao: "04/01/2023",
    dataCobranca: "19/10/2023",
    dataPagamento: null,
    valorNota: "296.00",
    documentoNotaFiscal: "NF43",
    documentoBoleto: "Boleto43",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 44,
    dataEmissao: "04/03/2023",
    dataCobranca: "20/08/2023",
    dataPagamento: null,
    valorNota: "467.00",
    documentoNotaFiscal: "NF44",
    documentoBoleto: "Boleto44",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Eduardo Oliveira",
    numeroNota: 45,
    dataEmissao: "26/01/2023",
    dataCobranca: "21/05/2023",
    dataPagamento: "01/09/2023",
    valorNota: "152.00",
    documentoNotaFiscal: "NF45",
    documentoBoleto: "Boleto45",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Mariana Silva",
    numeroNota: 46,
    dataEmissao: "26/06/2023",
    dataCobranca: "05/11/2023",
    dataPagamento: null,
    valorNota: "932.00",
    documentoNotaFiscal: "NF46",
    documentoBoleto: "Boleto46",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Eduardo Oliveira",
    numeroNota: 47,
    dataEmissao: "14/05/2023",
    dataCobranca: "07/09/2023",
    dataPagamento: "15/11/2023",
    valorNota: "435.00",
    documentoNotaFiscal: "NF47",
    documentoBoleto: "Boleto47",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Lúcia Oliveira",
    numeroNota: 48,
    dataEmissao: "22/02/2023",
    dataCobranca: "26/09/2023",
    dataPagamento: "28/04/2023",
    valorNota: "243.00",
    documentoNotaFiscal: "NF48",
    documentoBoleto: "Boleto48",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 49,
    dataEmissao: "28/08/2023",
    dataCobranca: "22/10/2023",
    dataPagamento: null,
    valorNota: "850.00",
    documentoNotaFiscal: "NF49",
    documentoBoleto: "Boleto49",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Alexandre Lima",
    numeroNota: 50,
    dataEmissao: "10/02/2023",
    dataCobranca: "04/03/2023",
    dataPagamento: null,
    valorNota: "843.00",
    documentoNotaFiscal: "NF50",
    documentoBoleto: "Boleto50",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Simone Santos",
    numeroNota: 51,
    dataEmissao: "14/10/2023",
    dataCobranca: "13/12/2023",
    dataPagamento: null,
    valorNota: "152.00",
    documentoNotaFiscal: "NF51",
    documentoBoleto: "Boleto51",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "João Silva",
    numeroNota: 52,
    dataEmissao: "14/07/2023",
    dataCobranca: "22/10/2023",
    dataPagamento: null,
    valorNota: "332.00",
    documentoNotaFiscal: "NF52",
    documentoBoleto: "Boleto52",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Alexandre Lima",
    numeroNota: 53,
    dataEmissao: "13/06/2023",
    dataCobranca: "19/07/2023",
    dataPagamento: null,
    valorNota: "999.00",
    documentoNotaFiscal: "NF53",
    documentoBoleto: "Boleto53",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Pedro Santos",
    numeroNota: 54,
    dataEmissao: "31/01/2023",
    dataCobranca: "29/05/2023",
    dataPagamento: "23/10/2023",
    valorNota: "318.00",
    documentoNotaFiscal: "NF54",
    documentoBoleto: "Boleto54",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Marcos Fernandes",
    numeroNota: 55,
    dataEmissao: "26/07/2023",
    dataCobranca: "19/08/2023",
    dataPagamento: "11/11/2023",
    valorNota: "261.00",
    documentoNotaFiscal: "NF55",
    documentoBoleto: "Boleto55",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Carlos Costa",
    numeroNota: 56,
    dataEmissao: "02/05/2023",
    dataCobranca: "01/07/2023",
    dataPagamento: "28/11/2023",
    valorNota: "397.00",
    documentoNotaFiscal: "NF56",
    documentoBoleto: "Boleto56",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Marcelo Fernandes",
    numeroNota: 57,
    dataEmissao: "23/03/2023",
    dataCobranca: "18/05/2023",
    dataPagamento: null,
    valorNota: "175.00",
    documentoNotaFiscal: "NF57",
    documentoBoleto: "Boleto57",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Helena Almeida",
    numeroNota: 58,
    dataEmissao: "25/02/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "890.00",
    documentoNotaFiscal: "NF58",
    documentoBoleto: "Boleto58",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 59,
    dataEmissao: "21/07/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "464.00",
    documentoNotaFiscal: "NF59",
    documentoBoleto: "Boleto59",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Lucas Oliveira",
    numeroNota: 60,
    dataEmissao: "07/07/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "347.00",
    documentoNotaFiscal: "NF60",
    documentoBoleto: "Boleto60",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Henrique Castro",
    numeroNota: 61,
    dataEmissao: "19/04/2023",
    dataCobranca: "14/06/2023",
    dataPagamento: null,
    valorNota: "978.00",
    documentoNotaFiscal: "NF61",
    documentoBoleto: "Boleto61",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Lucas Oliveira",
    numeroNota: 62,
    dataEmissao: "27/04/2023",
    dataCobranca: "07/12/2023",
    dataPagamento: null,
    valorNota: "965.00",
    documentoNotaFiscal: "NF62",
    documentoBoleto: "Boleto62",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 63,
    dataEmissao: "09/06/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "911.00",
    documentoNotaFiscal: "NF63",
    documentoBoleto: "Boleto63",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Paulo Mendes",
    numeroNota: 64,
    dataEmissao: "17/10/2023",
    dataCobranca: "21/10/2023",
    dataPagamento: null,
    valorNota: "183.00",
    documentoNotaFiscal: "NF64",
    documentoBoleto: "Boleto64",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Gustavo Rocha",
    numeroNota: 65,
    dataEmissao: "21/01/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "616.00",
    documentoNotaFiscal: "NF65",
    documentoBoleto: "Boleto65",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 66,
    dataEmissao: "02/04/2023",
    dataCobranca: "12/04/2023",
    dataPagamento: null,
    valorNota: "204.00",
    documentoNotaFiscal: "NF66",
    documentoBoleto: "Boleto66",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 67,
    dataEmissao: "25/01/2023",
    dataCobranca: "25/05/2023",
    dataPagamento: "12/08/2023",
    valorNota: "812.00",
    documentoNotaFiscal: "NF67",
    documentoBoleto: "Boleto67",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Isabela Pereira",
    numeroNota: 68,
    dataEmissao: "09/02/2023",
    dataCobranca: "08/06/2023",
    dataPagamento: null,
    valorNota: "814.00",
    documentoNotaFiscal: "NF68",
    documentoBoleto: "Boleto68",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Patrícia Castro",
    numeroNota: 69,
    dataEmissao: "03/03/2023",
    dataCobranca: "14/08/2023",
    dataPagamento: null,
    valorNota: "488.00",
    documentoNotaFiscal: "NF69",
    documentoBoleto: "Boleto69",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Carlos Mendes",
    numeroNota: 70,
    dataEmissao: "16/03/2023",
    dataCobranca: "30/04/2023",
    dataPagamento: "16/05/2023",
    valorNota: "534.00",
    documentoNotaFiscal: "NF70",
    documentoBoleto: "Boleto70",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Mariana Silva",
    numeroNota: 71,
    dataEmissao: "22/10/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "278.00",
    documentoNotaFiscal: "NF71",
    documentoBoleto: "Boleto71",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Juliana Almeida",
    numeroNota: 72,
    dataEmissao: "16/01/2023",
    dataCobranca: "30/08/2023",
    dataPagamento: "09/10/2023",
    valorNota: "927.00",
    documentoNotaFiscal: "NF72",
    documentoBoleto: "Boleto72",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Ricardo Lima",
    numeroNota: 73,
    dataEmissao: "26/01/2023",
    dataCobranca: "24/04/2023",
    dataPagamento: null,
    valorNota: "598.00",
    documentoNotaFiscal: "NF73",
    documentoBoleto: "Boleto73",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Henrique Castro",
    numeroNota: 74,
    dataEmissao: "17/06/2023",
    dataCobranca: "22/11/2023",
    dataPagamento: null,
    valorNota: "674.00",
    documentoNotaFiscal: "NF74",
    documentoBoleto: "Boleto74",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Isabela Pereira",
    numeroNota: 75,
    dataEmissao: "17/06/2023",
    dataCobranca: "24/08/2023",
    dataPagamento: null,
    valorNota: "191.00",
    documentoNotaFiscal: "NF75",
    documentoBoleto: "Boleto75",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Clara Rocha",
    numeroNota: 76,
    dataEmissao: "26/01/2023",
    dataCobranca: "25/07/2023",
    dataPagamento: null,
    valorNota: "229.00",
    documentoNotaFiscal: "NF76",
    documentoBoleto: "Boleto76",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Lúcia Oliveira",
    numeroNota: 77,
    dataEmissao: "12/04/2023",
    dataCobranca: "17/11/2023",
    dataPagamento: "18/07/2023",
    valorNota: "501.00",
    documentoNotaFiscal: "NF77",
    documentoBoleto: "Boleto77",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Juliana Almeida",
    numeroNota: 78,
    dataEmissao: "26/03/2023",
    dataCobranca: "05/09/2023",
    dataPagamento: null,
    valorNota: "289.00",
    documentoNotaFiscal: "NF78",
    documentoBoleto: "Boleto78",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Clara Rocha",
    numeroNota: 79,
    dataEmissao: "03/04/2023",
    dataCobranca: "19/09/2023",
    dataPagamento: null,
    valorNota: "830.00",
    documentoNotaFiscal: "NF79",
    documentoBoleto: "Boleto79",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Larissa Martins",
    numeroNota: 80,
    dataEmissao: "04/03/2023",
    dataCobranca: "04/06/2023",
    dataPagamento: null,
    valorNota: "548.00",
    documentoNotaFiscal: "NF80",
    documentoBoleto: "Boleto80",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Raphael Fernandes",
    numeroNota: 81,
    dataEmissao: "16/08/2023",
    dataCobranca: "14/10/2023",
    dataPagamento: null,
    valorNota: "221.00",
    documentoNotaFiscal: "NF81",
    documentoBoleto: "Boleto81",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Carlos Mendes",
    numeroNota: 82,
    dataEmissao: "16/08/2023",
    dataCobranca: "16/11/2023",
    dataPagamento: null,
    valorNota: "781.00",
    documentoNotaFiscal: "NF82",
    documentoBoleto: "Boleto82",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 83,
    dataEmissao: "04/06/2023",
    dataCobranca: "28/08/2023",
    dataPagamento: "28/09/2023",
    valorNota: "1000.00",
    documentoNotaFiscal: "NF83",
    documentoBoleto: "Boleto83",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Simone Santos",
    numeroNota: 84,
    dataEmissao: "20/08/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "237.00",
    documentoNotaFiscal: "NF84",
    documentoBoleto: "Boleto84",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Helena Almeida",
    numeroNota: 85,
    dataEmissao: "29/07/2023",
    dataCobranca: "29/11/2023",
    dataPagamento: null,
    valorNota: "204.00",
    documentoNotaFiscal: "NF85",
    documentoBoleto: "Boleto85",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Luciana Costa",
    numeroNota: 86,
    dataEmissao: "13/01/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "856.00",
    documentoNotaFiscal: "NF86",
    documentoBoleto: "Boleto86",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Lúcia Oliveira",
    numeroNota: 87,
    dataEmissao: "24/01/2023",
    dataCobranca: "13/04/2023",
    dataPagamento: null,
    valorNota: "773.00",
    documentoNotaFiscal: "NF87",
    documentoBoleto: "Boleto87",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 88,
    dataEmissao: "08/04/2023",
    dataCobranca: "17/05/2023",
    dataPagamento: null,
    valorNota: "232.00",
    documentoNotaFiscal: "NF88",
    documentoBoleto: "Boleto88",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Fábio Silva",
    numeroNota: 89,
    dataEmissao: "20/08/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "640.00",
    documentoNotaFiscal: "NF89",
    documentoBoleto: "Boleto89",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Silvia Rocha",
    numeroNota: 90,
    dataEmissao: "12/04/2023",
    dataCobranca: "27/06/2023",
    dataPagamento: null,
    valorNota: "281.00",
    documentoNotaFiscal: "NF90",
    documentoBoleto: "Boleto90",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 91,
    dataEmissao: "02/01/2023",
    dataCobranca: "22/04/2023",
    dataPagamento: "28/05/2023",
    valorNota: "565.00",
    documentoNotaFiscal: "NF91",
    documentoBoleto: "Boleto91",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Carlos Costa",
    numeroNota: 92,
    dataEmissao: "29/04/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "178.00",
    documentoNotaFiscal: "NF92",
    documentoBoleto: "Boleto92",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Renata Rodrigues",
    numeroNota: 93,
    dataEmissao: "10/09/2023",
    dataCobranca: "08/11/2023",
    dataPagamento: null,
    valorNota: "381.00",
    documentoNotaFiscal: "NF93",
    documentoBoleto: "Boleto93",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Tatiane Pereira",
    numeroNota: 94,
    dataEmissao: "11/04/2023",
    dataCobranca: "13/05/2023",
    dataPagamento: null,
    valorNota: "821.00",
    documentoNotaFiscal: "NF94",
    documentoBoleto: "Boleto94",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Maria Oliveira",
    numeroNota: 95,
    dataEmissao: "05/01/2023",
    dataCobranca: "03/11/2023",
    dataPagamento: "26/04/2023",
    valorNota: "728.00",
    documentoNotaFiscal: "NF95",
    documentoBoleto: "Boleto95",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Fernanda Lima",
    numeroNota: 96,
    dataEmissao: "02/07/2023",
    dataCobranca: "14/07/2023",
    dataPagamento: null,
    valorNota: "391.00",
    documentoNotaFiscal: "NF96",
    documentoBoleto: "Boleto96",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Rodrigo Fernandes",
    numeroNota: 97,
    dataEmissao: "25/02/2023",
    dataCobranca: "10/04/2023",
    dataPagamento: "23/08/2023",
    valorNota: "249.00",
    documentoNotaFiscal: "NF97",
    documentoBoleto: "Boleto97",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 98,
    dataEmissao: "11/07/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "860.00",
    documentoNotaFiscal: "NF98",
    documentoBoleto: "Boleto98",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Henrique Castro",
    numeroNota: 99,
    dataEmissao: "17/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "742.00",
    documentoNotaFiscal: "NF99",
    documentoBoleto: "Boleto99",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Clara Rocha",
    numeroNota: 100,
    dataEmissao: "08/01/2023",
    dataCobranca: "24/01/2023",
    dataPagamento: null,
    valorNota: "423.00",
    documentoNotaFiscal: "NF100",
    documentoBoleto: "Boleto100",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Gabriel Sousa",
    numeroNota: 101,
    dataEmissao: "16/10/2023",
    dataCobranca: "09/12/2023",
    dataPagamento: null,
    valorNota: "390.00",
    documentoNotaFiscal: "NF101",
    documentoBoleto: "Boleto101",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Marcelo Santos",
    numeroNota: 102,
    dataEmissao: "28/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "718.00",
    documentoNotaFiscal: "NF102",
    documentoBoleto: "Boleto102",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Silvia Rocha",
    numeroNota: 103,
    dataEmissao: "29/01/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "578.00",
    documentoNotaFiscal: "NF103",
    documentoBoleto: "Boleto103",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Priscila Rodrigues",
    numeroNota: 104,
    dataEmissao: "03/07/2023",
    dataCobranca: "06/08/2023",
    dataPagamento: "23/08/2023",
    valorNota: "972.00",
    documentoNotaFiscal: "NF104",
    documentoBoleto: "Boleto104",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 105,
    dataEmissao: "05/03/2023",
    dataCobranca: "10/06/2023",
    dataPagamento: null,
    valorNota: "776.00",
    documentoNotaFiscal: "NF105",
    documentoBoleto: "Boleto105",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Larissa Martins",
    numeroNota: 106,
    dataEmissao: "14/10/2023",
    dataCobranca: "14/11/2023",
    dataPagamento: "09/12/2023",
    valorNota: "190.00",
    documentoNotaFiscal: "NF106",
    documentoBoleto: "Boleto106",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Renata Rodrigues",
    numeroNota: 107,
    dataEmissao: "02/02/2023",
    dataCobranca: "16/07/2023",
    dataPagamento: null,
    valorNota: "461.00",
    documentoNotaFiscal: "NF107",
    documentoBoleto: "Boleto107",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 108,
    dataEmissao: "19/07/2023",
    dataCobranca: "03/09/2023",
    dataPagamento: "08/09/2023",
    valorNota: "494.00",
    documentoNotaFiscal: "NF108",
    documentoBoleto: "Boleto108",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 109,
    dataEmissao: "01/04/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "607.00",
    documentoNotaFiscal: "NF109",
    documentoBoleto: "Boleto109",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Marcos Fernandes",
    numeroNota: 110,
    dataEmissao: "04/08/2023",
    dataCobranca: "20/10/2023",
    dataPagamento: "24/08/2023",
    valorNota: "452.00",
    documentoNotaFiscal: "NF110",
    documentoBoleto: "Boleto110",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Diego Lima",
    numeroNota: 111,
    dataEmissao: "03/06/2023",
    dataCobranca: "04/09/2023",
    dataPagamento: "25/11/2023",
    valorNota: "279.00",
    documentoNotaFiscal: "NF111",
    documentoBoleto: "Boleto111",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Paulo Mendes",
    numeroNota: 112,
    dataEmissao: "25/03/2023",
    dataCobranca: "22/08/2023",
    dataPagamento: null,
    valorNota: "233.00",
    documentoNotaFiscal: "NF112",
    documentoBoleto: "Boleto112",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Thiago Mendes",
    numeroNota: 113,
    dataEmissao: "18/04/2023",
    dataCobranca: "28/06/2023",
    dataPagamento: null,
    valorNota: "736.00",
    documentoNotaFiscal: "NF113",
    documentoBoleto: "Boleto113",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Paulo Mendes",
    numeroNota: 114,
    dataEmissao: "24/03/2023",
    dataCobranca: "24/08/2023",
    dataPagamento: "03/10/2023",
    valorNota: "471.00",
    documentoNotaFiscal: "NF114",
    documentoBoleto: "Boleto114",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Viviane Rodrigues",
    numeroNota: 115,
    dataEmissao: "04/04/2023",
    dataCobranca: "29/09/2023",
    dataPagamento: null,
    valorNota: "781.00",
    documentoNotaFiscal: "NF115",
    documentoBoleto: "Boleto115",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Mariana Silva",
    numeroNota: 116,
    dataEmissao: "19/03/2023",
    dataCobranca: "22/09/2023",
    dataPagamento: null,
    valorNota: "533.00",
    documentoNotaFiscal: "NF116",
    documentoBoleto: "Boleto116",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Simone Santos",
    numeroNota: 117,
    dataEmissao: "05/03/2023",
    dataCobranca: "24/04/2023",
    dataPagamento: "08/05/2023",
    valorNota: "350.00",
    documentoNotaFiscal: "NF117",
    documentoBoleto: "Boleto117",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 118,
    dataEmissao: "24/09/2023",
    dataCobranca: "08/11/2023",
    dataPagamento: null,
    valorNota: "777.00",
    documentoNotaFiscal: "NF118",
    documentoBoleto: "Boleto118",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 119,
    dataEmissao: "03/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "444.00",
    documentoNotaFiscal: "NF119",
    documentoBoleto: "Boleto119",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Diego Lima",
    numeroNota: 120,
    dataEmissao: "07/07/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "522.00",
    documentoNotaFiscal: "NF120",
    documentoBoleto: "Boleto120",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Gabriel Sousa",
    numeroNota: 121,
    dataEmissao: "26/08/2023",
    dataCobranca: "25/10/2023",
    dataPagamento: null,
    valorNota: "784.00",
    documentoNotaFiscal: "NF121",
    documentoBoleto: "Boleto121",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Camila Rodrigues",
    numeroNota: 122,
    dataEmissao: "27/09/2023",
    dataCobranca: "06/12/2023",
    dataPagamento: "22/10/2023",
    valorNota: "456.00",
    documentoNotaFiscal: "NF122",
    documentoBoleto: "Boleto122",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 123,
    dataEmissao: "29/03/2023",
    dataCobranca: "19/10/2023",
    dataPagamento: null,
    valorNota: "928.00",
    documentoNotaFiscal: "NF123",
    documentoBoleto: "Boleto123",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Priscila Rodrigues",
    numeroNota: 124,
    dataEmissao: "11/02/2023",
    dataCobranca: "19/04/2023",
    dataPagamento: null,
    valorNota: "976.00",
    documentoNotaFiscal: "NF124",
    documentoBoleto: "Boleto124",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Roberto Costa",
    numeroNota: 125,
    dataEmissao: "24/02/2023",
    dataCobranca: "18/06/2023",
    dataPagamento: null,
    valorNota: "482.00",
    documentoNotaFiscal: "NF125",
    documentoBoleto: "Boleto125",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Carlos Mendes",
    numeroNota: 126,
    dataEmissao: "01/08/2023",
    dataCobranca: "14/11/2023",
    dataPagamento: null,
    valorNota: "729.00",
    documentoNotaFiscal: "NF126",
    documentoBoleto: "Boleto126",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Gabriel Sousa",
    numeroNota: 127,
    dataEmissao: "12/06/2023",
    dataCobranca: "28/09/2023",
    dataPagamento: null,
    valorNota: "894.00",
    documentoNotaFiscal: "NF127",
    documentoBoleto: "Boleto127",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Thiago Mendes",
    numeroNota: 128,
    dataEmissao: "11/12/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "908.00",
    documentoNotaFiscal: "NF128",
    documentoBoleto: "Boleto128",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Isabela Pereira",
    numeroNota: 129,
    dataEmissao: "14/01/2023",
    dataCobranca: "02/11/2023",
    dataPagamento: null,
    valorNota: "154.00",
    documentoNotaFiscal: "NF129",
    documentoBoleto: "Boleto129",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Diego Lima",
    numeroNota: 130,
    dataEmissao: "13/03/2023",
    dataCobranca: "18/03/2023",
    dataPagamento: "10/08/2023",
    valorNota: "269.00",
    documentoNotaFiscal: "NF130",
    documentoBoleto: "Boleto130",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Clara Rocha",
    numeroNota: 131,
    dataEmissao: "05/02/2023",
    dataCobranca: "22/10/2023",
    dataPagamento: null,
    valorNota: "264.00",
    documentoNotaFiscal: "NF131",
    documentoBoleto: "Boleto131",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Monica Lima",
    numeroNota: 132,
    dataEmissao: "05/02/2023",
    dataCobranca: "16/04/2023",
    dataPagamento: null,
    valorNota: "324.00",
    documentoNotaFiscal: "NF132",
    documentoBoleto: "Boleto132",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Renata Rodrigues",
    numeroNota: 133,
    dataEmissao: "17/02/2023",
    dataCobranca: "12/07/2023",
    dataPagamento: "02/08/2023",
    valorNota: "940.00",
    documentoNotaFiscal: "NF133",
    documentoBoleto: "Boleto133",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "André Silva",
    numeroNota: 134,
    dataEmissao: "09/06/2023",
    dataCobranca: "08/10/2023",
    dataPagamento: null,
    valorNota: "898.00",
    documentoNotaFiscal: "NF134",
    documentoBoleto: "Boleto134",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Amanda Santos",
    numeroNota: 135,
    dataEmissao: "11/02/2023",
    dataCobranca: "26/11/2023",
    dataPagamento: "03/07/2023",
    valorNota: "734.00",
    documentoNotaFiscal: "NF135",
    documentoBoleto: "Boleto135",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Mariana Silva",
    numeroNota: 136,
    dataEmissao: "26/04/2023",
    dataCobranca: "10/11/2023",
    dataPagamento: "24/11/2023",
    valorNota: "488.00",
    documentoNotaFiscal: "NF136",
    documentoBoleto: "Boleto136",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Pedro Santos",
    numeroNota: 137,
    dataEmissao: "16/01/2023",
    dataCobranca: "03/05/2023",
    dataPagamento: null,
    valorNota: "442.00",
    documentoNotaFiscal: "NF137",
    documentoBoleto: "Boleto137",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 138,
    dataEmissao: "05/12/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "751.00",
    documentoNotaFiscal: "NF138",
    documentoBoleto: "Boleto138",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Ana Pereira",
    numeroNota: 139,
    dataEmissao: "11/08/2023",
    dataCobranca: "11/08/2023",
    dataPagamento: null,
    valorNota: "516.00",
    documentoNotaFiscal: "NF139",
    documentoBoleto: "Boleto139",
    statusNota: "Cobrança realizada",
  },
  {
    nomePagador: "Fábio Silva",
    numeroNota: 140,
    dataEmissao: "22/01/2023",
    dataCobranca: "14/10/2023",
    dataPagamento: "08/12/2023",
    valorNota: "973.00",
    documentoNotaFiscal: "NF140",
    documentoBoleto: "Boleto140",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 141,
    dataEmissao: "11/03/2023",
    dataCobranca: "19/06/2023",
    dataPagamento: "23/06/2023",
    valorNota: "206.00",
    documentoNotaFiscal: "NF141",
    documentoBoleto: "Boleto141",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Ricardo Lima",
    numeroNota: 142,
    dataEmissao: "15/03/2023",
    dataCobranca: "02/09/2023",
    dataPagamento: "14/08/2023",
    valorNota: "861.00",
    documentoNotaFiscal: "NF142",
    documentoBoleto: "Boleto142",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 143,
    dataEmissao: "03/04/2023",
    dataCobranca: "18/04/2023",
    dataPagamento: "31/07/2023",
    valorNota: "818.00",
    documentoNotaFiscal: "NF143",
    documentoBoleto: "Boleto143",
    statusNota: "Pagamento realizado",
  },
  {
    nomePagador: "Gustavo Rocha",
    numeroNota: 144,
    dataEmissao: "12/08/2023",
    dataCobranca: "22/09/2023",
    dataPagamento: null,
    valorNota: "355.00",
    documentoNotaFiscal: "NF144",
    documentoBoleto: "Boleto144",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Beatriz Almeida",
    numeroNota: 145,
    dataEmissao: "08/03/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "661.00",
    documentoNotaFiscal: "NF145",
    documentoBoleto: "Boleto145",
    statusNota: "Emitida",
  },
  {
    nomePagador: "César Santos",
    numeroNota: 146,
    dataEmissao: "11/04/2023",
    dataCobranca: "07/05/2023",
    dataPagamento: null,
    valorNota: "232.00",
    documentoNotaFiscal: "NF146",
    documentoBoleto: "Boleto146",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Camila Rodrigues",
    numeroNota: 147,
    dataEmissao: "16/08/2023",
    dataCobranca: "16/11/2023",
    dataPagamento: null,
    valorNota: "457.00",
    documentoNotaFiscal: "NF147",
    documentoBoleto: "Boleto147",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Renata Pereira",
    numeroNota: 148,
    dataEmissao: "12/11/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "717.00",
    documentoNotaFiscal: "NF148",
    documentoBoleto: "Boleto148",
    statusNota: "Emitida",
  },
  {
    nomePagador: "Luiz Rocha",
    numeroNota: 149,
    dataEmissao: "10/02/2023",
    dataCobranca: "05/08/2023",
    dataPagamento: null,
    valorNota: "730.00",
    documentoNotaFiscal: "NF149",
    documentoBoleto: "Boleto149",
    statusNota: "Pagamento em atraso",
  },
  {
    nomePagador: "Fernando Costa",
    numeroNota: 150,
    dataEmissao: "02/12/2023",
    dataCobranca: null,
    dataPagamento: null,
    valorNota: "380.00",
    documentoNotaFiscal: "NF150",
    documentoBoleto: "Boleto150",
    statusNota: "Emitida",
  },
];

var somaTotal = dados.reduce(function (x, y) {
  return x + parseFloat(y.valorNota);
}, 0);

var semCobranca = dados
  .filter((a) => a.statusNota == "Emitida")
  .reduce(function (x, y) {
    return x + parseFloat(y.valorNota);
  }, 0);

var inadimplencia = dados
  .filter((a) => a.statusNota == "Pagamento em atraso")
  .reduce(function (x, y) {
    return x + parseFloat(y.valorNota);
  }, 0);

var avencer = dados
  .filter((a) => a.statusNota == "Cobrança realizada")
  .reduce(function (x, y) {
    return x + parseFloat(y.valorNota);
  }, 0);

var pagas = dados
  .filter((a) => a.statusNota == "Pagamento realizado")
  .reduce(function (x, y) {
    return x + parseFloat(y.valorNota);
  }, 0);

const meses = [
  { mes: "Janeiro", numero: 1 },
  { mes: "Fevereiro", numero: 2 },
  { mes: "Março", numero: 3 },
  { mes: "Abril", numero: 4 },
  { mes: "Maio", numero: 5 },
  { mes: "Junho", numero: 6 },
  { mes: "Julho", numero: 7 },
  { mes: "Agosto", numero: 8 },
  { mes: "Setembro", numero: 9 },
  { mes: "Outubro", numero: 10 },
  { mes: "Novembro", numero: 11 },
  { mes: "Dezembro", numero: 12 },
];

const inadimplenciaMes = meses.map((mes) => {
  return dados.filter(
    (dado) =>
      dado.statusNota == "Pagamento em atraso" &&
      parseInt(dado?.dataCobranca.split("/")[1]) == mes.numero
  ).length;
});

const pagamentoMes = meses.map((mes) => {
  return dados.filter(
    (dado) =>
      dado.statusNota == "Pagamento realizado" &&
      parseInt(dado?.dataCobranca.split("/")[1]) == mes.numero
  ).length;
});

var auxPagamentoSoma = 0;
const pagamentoSoma = pagamentoMes.map((valor) => {
  auxPagamentoSoma += valor;

  return auxPagamentoSoma;
});

var auxInadimplenciaSoma = 0;
const inadimplenciaSoma = inadimplenciaMes.map((valor) => {
  auxInadimplenciaSoma += valor;

  return auxInadimplenciaSoma;
});
